- name: setup {{ role_name }} wrapper version
  template:
    src: "{{ gradle.wrapper_template | default('gradle-wrapper.properties.j2') }}"
    dest: "{{ workdir }}/gradle/wrapper/gradle-wrapper.properties"
