- name: clone {{ repository_url }} repository
  git:
    repo: "{{ repository_url }}"
    dest: "{{ workdir }}"
    update: false
    accept_hostkey: true
    version: "{{ repository_version|default('HEAD') }}"
