name: Lint
on: [push, pull_request]
jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: playbooks/all
